version: '3.1'
services:
    jenkins:
        container_name: jenkins
        restart: always
        ports:
            - '80:8080'
            - '50000:50000'
        image: localhost:5000/jenkins
    jenkins-slave:
        container_name: jenkins-slave
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:80'
        image: localhost:5000/jenkins-slave
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - jenkins
