version: '3.1'
services:
    jenkins:
        container_name: jenkins-master
        privileged: true
        restart: always
        user: root
        ports:
            - '80:8080'
            - '50000:50000'
        image: jenkinsci/blueocean
        volumes:
            - /Users/shiva/workspace/jenkins/docker_1/jenkins-data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /Users/shiva:/home
